name: Deploy to API Production
on:
  push:
    branches:
      - master

jobs:
  FTP-Deploy-Action:
    name: FTP-Deploy-Action
    runs-on: ubuntu-latest
    steps:
    - name: Get the latest code
      uses: actions/checkout@v2.1.0
    - uses: actions/setup-node@master
    - name: Copy .env
      run: php -r "file_exists('.env') || copy('.env.example', '.env')"
    - name: Install Depedencies
      run: composer update --ignore-platform-reqs
    - name: Generate key
      run: php artisan key:generate
    - name: Genenrate storage link
      run: php artisan storage:link
    - name: Directory Permission
      run: chmod -R 777 storage bootstrap/cache
    - name: FTP-Deploy-Action
      uses: SamKirkland/FTP-Deploy-Action@4.3.0
      with:
        server: ${{ secrets.FTP_SERVER }}
        username: ${{ secrets.FTP_USERNAME }}
        password: ${{ secrets.FTP_PASSWORD }}
        server-dir: /